-- 業務日報 提出管理 / Supabase SQL Editor で実行
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  department text,
  role text not null default 'member' check (role in ('member', 'manager')),
  manager_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  report_date date not null,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, report_date)
);
create index if not exists daily_reports_user_date_idx on public.daily_reports(user_id, report_date);
create index if not exists profiles_manager_idx on public.profiles(manager_id);

-- 将来、祝日・有休・出張などを登録する際の拡張用テーブル（初期版の画面では未使用）
create table if not exists public.non_working_days (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  target_date date not null,
  reason text not null default 'other',
  created_at timestamptz not null default now(),
  unique (user_id, target_date)
);

alter table public.profiles enable row level security;
alter table public.daily_reports enable row level security;
alter table public.non_working_days enable row level security;

-- profiles: 自分自身、および manager_id が自分の直属メンバーだけを読める
create policy "profiles: own or direct reports only" on public.profiles for select to authenticated
  using (id = auth.uid() or manager_id = auth.uid());

-- 日報: 自分自身または直属メンバーのものだけ読める
create policy "reports: own or direct reports only" on public.daily_reports for select to authenticated
  using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = daily_reports.user_id and p.manager_id = auth.uid()));
create policy "reports: insert own only" on public.daily_reports for insert to authenticated
  with check (user_id = auth.uid());

-- 将来の対象外日も本人・直属上司に限定
create policy "nonworking: own or direct reports only" on public.non_working_days for select to authenticated
  using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = non_working_days.user_id and p.manager_id = auth.uid()));
create policy "nonworking: own only" on public.non_working_days for insert to authenticated with check (user_id = auth.uid());

-- profiles は SQL Editor / 管理バックエンドでのみ作成・更新する運用です。
-- ブラウザには anon key だけを置き、service_role key は絶対に置かないでください。
